name: Release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - v*.*.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: service/go.mod
          cache-dependency-path: service/go.sum
      - name: Run Test
        run: ./build.sh build deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LAMBDA_HOSTNAME: ${{ vars.LAMBDA_HOSTNAME }}
